
version: '3.7'
services:

    backend:

        container_name: backend

        build: .\api_java\simple-api-student-main\simple-api-student-main\

        environment:

            DB_host: database

            DB_port: 5432

            DB_name: db

            DB_user: usr

            DB_mdp: pswd

        ports:

            - "8080:8080"

        networks:

            - app-network

        depends_on:

            - database

    database:

        container_name: database

        build: .\database\

        environment:

            POSTGRES_DB: db

            POSTGRES_USER: usr

            POSTGRES_PASSWORD: pswd

        volumes:

            - postgresdata:/var/lib/postgresql/data

        networks:

            - app-network

    httpd:

        container_name: httpd

        build: .\frontend\

        environment:

            BACKEND_host: backend

        ports:

            - "80:80"

        networks:

            - app-network

        depends_on:

            - backend

networks:

    app-network:

 
volumes:

    postgresdata:
