all:
 vars:
   ansible_user: centos
   ansible_ssh_private_key_file: /home/come/.ssh/id_rsa
   ansible_python_interpreter: "/usr/bin/env python"
 children:
   prod:
     hosts: come.richard.takima.cloud